version: "3"
services:
  api:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: gameconf-api
  client:
    build: ./client
    ports:
      - "80:80"
    container_name: gameconf-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: gameconf-db
